name: Jest Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main
      - deploy/*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    name: Jest Test
    runs-on: ubuntu-latest

    steps:
      - name: GitHub checkout
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test:ci
